# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target ‘Chat Socket’ do
    pod 'Socket.IO-Client-Swift', '~> 11.0.2' # Or latest version
end
